using System.Text.Json;
using System.Text.Json.Serialization;

namespace Millrace;

/// <summary>
/// Identifies a workflow instance. Generated by the engine; opaque to storage providers.
/// </summary>
[JsonConverter(typeof(WorkflowInstanceIdJsonConverter))]
public readonly record struct WorkflowInstanceId(Guid Value)
{
    public static WorkflowInstanceId New() => new(Guid.CreateVersion7());

    public static WorkflowInstanceId New(TimeProvider time) => new(Guid.CreateVersion7(time.GetUtcNow()));

    public override string ToString() => Value.ToString("n");
}

/// <summary>Serializes <see cref="WorkflowInstanceId"/> as a bare GUID string.</summary>
public sealed class WorkflowInstanceIdJsonConverter : JsonConverter<WorkflowInstanceId>
{
    public override WorkflowInstanceId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new(reader.GetGuid());

    public override void Write(Utf8JsonWriter writer, WorkflowInstanceId value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);

    public override WorkflowInstanceId ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new(Guid.Parse(reader.GetString()!));

    public override void WriteAsPropertyName(Utf8JsonWriter writer, WorkflowInstanceId value, JsonSerializerOptions options)
        => writer.WritePropertyName(value.Value.ToString("d"));
}
